// 由 tools/gen_story.py 自动生成，请勿手改
// 图片索引表：下标即剧本节点里的资源号
export const IMG = [
  "/common/img/b/box_seat.png",
  "/common/img/b/classroom1.png",
  "/common/img/b/classroom2.png",
  "/common/img/b/classroom3.png",
  "/common/img/b/classroom_floor.png",
  "/common/img/b/computer_desk.png",
  "/common/img/b/elevator.png",
  "/common/img/b/heavenly_altar.png",
  "/common/img/b/heavenly_altar_focus.png",
  "/common/img/b/hotel_corridor.png",
  "/common/img/b/hotel_entrance.png",
  "/common/img/b/hotel_livingroom.png",
  "/common/img/b/hotel_restaurant.png",
  "/common/img/b/kitchen.png",
  "/common/img/b/living_room1.png",
  "/common/img/b/living_room2.png",
  "/common/img/b/moon.png",
  "/common/img/b/moon_all.png",
  "/common/img/b/neighborhood.png",
  "/common/img/b/neighborhood_vague.png",
  "/common/img/b/noctella_background.png",
  "/common/img/b/pavilion.png",
  "/common/img/b/riverside_road.png",
  "/common/img/b/riverside_road2.png",
  "/common/img/b/room1_4.png",
  "/common/img/b/school1.png",
  "/common/img/b/school2.png",
  "/common/img/b/shopping_mall.png",
  "/common/img/b/sportsroom.png",
  "/common/img/b/stair_landing.png",
  "/common/img/b/street1_1.png",
  "/common/img/b/street1_2.png",
  "/common/img/b/street2_1.png",
  "/common/img/b/street2_2.png",
  "/common/img/b/street3_1.png",
  "/common/img/b/tearoom.png",
  "/common/img/b/test_paper.png",
  "/common/img/b/urban_skies.png",
  "/common/img/s/000.png",
  "/common/img/s/001.png",
  "/common/img/s/002.png",
  "/common/img/s/003.png",
  "/common/img/s/004.png",
  "/common/img/s/005.png",
  "/common/img/s/006.png",
  "/common/img/s/007.png",
  "/common/img/s/008.png",
  "/common/img/s/009.png",
  "/common/img/s/010.png",
  "/common/img/s/011.png",
  "/common/img/s/012.png",
  "/common/img/s/013.png",
  "/common/img/s/014.png",
  "/common/img/s/015.png",
  "/common/img/s/016.png",
  "/common/img/s/017.png",
  "/common/img/s/018.png",
  "/common/img/s/019.png",
  "/common/img/s/020.png",
  "/common/img/s/021.png",
  "/common/img/s/022.png",
  "/common/img/s/023.png",
  "/common/img/s/024.png",
  "/common/img/s/025.png",
  "/common/img/s/026.png",
  "/common/img/s/027.png",
  "/common/img/s/028.png",
  "/common/img/s/029.png",
  "/common/img/s/030.png",
  "/common/img/s/031.png",
  "/common/img/s/032.png",
  "/common/img/s/033.png",
  "/common/img/s/034.png",
  "/common/img/s/035.png",
  "/common/img/s/036.png",
  "/common/img/s/037.png",
  "/common/img/s/038.png",
  "/common/img/s/039.png",
  "/common/img/s/040.png",
  "/common/img/s/041.png",
  "/common/img/s/042.png",
  "/common/img/s/043.png",
  "/common/img/s/044.png",
  "/common/img/s/045.png",
  "/common/img/s/046.png",
  "/common/img/s/047.png",
  "/common/img/s/048.png",
  "/common/img/s/049.png",
  "/common/img/s/050.png",
  "/common/img/s/051.png",
  "/common/img/s/052.png",
  "/common/img/s/053.png",
  "/common/img/s/054.png",
  "/common/img/c/cg_001.png",
  "/common/img/c/cg_002.png",
  "/common/img/c/cg_003.png",
  "/common/img/c/cg_004.png",
  "/common/img/c/cg_005.png",
  "/common/img/c/cg_006.png",
  "/common/img/c/cg_007.png",
  "/common/img/c/cg_008.png",
  "/common/img/c/cg_009.png",
  "/common/img/c/cg_010.png",
  "/common/img/c/cg_011.png",
  "/common/img/c/cg_012.png",
  "/common/img/c/cg_013.png",
  "/common/img/c/cg_noctella_descend.png",
  "/common/img/c/cg_noctella_descend_full.png",
  "/common/img/c/sd_001.png",
  "/common/img/c/sd_002.png",
  "/common/img/c/sd_003.png",
  "/common/img/c/sd_004.png",
  "/common/img/c/sd_005.png",
  "/common/img/c/sd_006.png",
  "/common/img/c/sd_007.png",
  "/common/img/c/sd_008.png",
  "/common/img/c/sd_009.png",
  "/common/img/c/sd_010.png",
  "/common/img/c/sd_011.png",
  "/common/img/c/sd_012.png",
  "/common/img/c/sd_013.png",
  "/common/img/c/sd_014.png",
  "/common/img/c/sd_015.png",
  "/common/img/c/sd_016.png",
  "/common/img/c/sd_017.png",
  "/common/img/c/sd_018.png",
  "/common/img/c/sd_019.png",
]

// 背景代号 -> 图片下标（-1 纯黑 / -2 纯白）
export const BG = {
  "black": -1,
  "white": -2,
  "box_seat": 0,
  "classroom1": 1,
  "classroom2": 2,
  "classroom3": 3,
  "classroom_floor": 4,
  "computer_desk": 5,
  "elevator": 6,
  "heavenly_altar": 7,
  "heavenly_altar_focus": 8,
  "hotel_corridor": 9,
  "hotel_entrance": 10,
  "hotel_livingroom": 11,
  "hotel_restaurant": 12,
  "kitchen": 13,
  "living_room1": 14,
  "living_room2": 15,
  "moon": 16,
  "moon_all": 17,
  "neighborhood": 18,
  "neighborhood_vague": 19,
  "noctella_background": 20,
  "pavilion": 21,
  "riverside_road": 22,
  "riverside_road2": 23,
  "room1_4": 24,
  "school1": 25,
  "school2": 26,
  "shopping_mall": 27,
  "sportsroom": 28,
  "stair_landing": 29,
  "street1_1": 30,
  "street1_2": 31,
  "street2_1": 32,
  "street2_2": 33,
  "street3_1": 34,
  "tearoom": 35,
  "test_paper": 36,
  "urban_skies": 37,
}

// 立绘 "角色码|表情" -> 图片下标
export const SP = {
  "father|shadow": 38,
  "jwq|叹气": 39,
  "jwq|坚定": 40,
  "jwq|嫌弃": 41,
  "jwq|尴尬": 42,
  "jwq|平静": 43,
  "jwq|微笑": 44,
  "jwq|恐惧": 45,
  "jwq|指摘": 46,
  "jwq|挺好颜": 47,
  "jwq|游刃有余": 48,
  "jwq|痛苦": 49,
  "jwq|眯眼": 50,
  "jwq|空洞": 51,
  "jwq|空洞2": 52,
  "jwq|落寞": 53,
  "jwq|计划通": 54,
  "lx|发情": 55,
  "lx|叹气": 56,
  "lx|哭哭": 57,
  "lx|害羞": 58,
  "lx|平静": 59,
  "lx|平静带怒": 60,
  "lx|开心": 61,
  "lx|微笑": 62,
  "lx|忧伤": 63,
  "lx|惊讶": 64,
  "lx|无语": 65,
  "lx|欲言又止": 66,
  "lx|白眼": 67,
  "lx|萌怒": 68,
  "lx|闭眼微笑": 69,
  "lx|鼓嘴气气": 70,
  "mother|shadow": 71,
  "noctella|微笑": 72,
  "noctella|无口": 73,
  "noctella|神之笑": 74,
  "other|renchao": 75,
  "ty_a|shadow": 76,
  "xl_l|卖萌叹气": 77,
  "xl_l|卖萌哭哭": 78,
  "xl_l|卖萌惊讶": 79,
  "xl_l|卖萌气气": 80,
  "xl_l|卖萌疑惑": 81,
  "xl_l|害羞": 82,
  "xl_l|抽泣": 83,
  "xl_l|温柔": 84,
  "xl|卖萌叹气": 85,
  "xl|卖萌哭哭": 86,
  "xl|卖萌惊讶": 87,
  "xl|卖萌气气": 88,
  "xl|卖萌疑惑": 89,
  "xl|害羞": 90,
  "xl|抽泣": 91,
  "xl|温柔": 92,
}
